version: '3.8'

services:
  dss-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - BQ_PROJECT_ID=your-project-id
      - BQ_DATASET_ID=nyc_taxi_dw
    volumes:
      - ./saved_models:/app/saved_models
      - ./dataset:/app/dataset
    restart: always
